### PR TITLE
update sticky

### PR DESCRIPTION
**Pull request by coreysyms**
Addition of css left on sticky elements to keep them in place

### CODE REVIEW

**Comment by zurbchris** [comment]
Is this for the issue on safari where the sticky element was floating left when it hit `position: fixed;`?

**Comment by coreysyms** [comment]
yes

**Comment by rafibomb** [comment]
Thanks! @coreysyms We'll be testing for merge soon!

**Comment by zurbchris** [comment]
I updated your work to avoid repeating code a bit, but took the PR. Not sure why you're not getting credit for it. 
Thanks for the help!

**Comment by coreysyms** [comment]
where's my credit! lol. ;) Glad it worked.

**Comment by zurbchris** [comment]
I don't know! I merged it in from your branch... no credit given. Git Problems yo!

**Pull request closed without merging**
