### PR TITLE
Updated meteor package file.

### PR DESCRIPTION
**Pull request by natecox**
* Package file now includes:
  * Minified and non minified css and js
  * All sass files

To reference a file you use the following format (sass import given as
an example):

    @import "{zurb:foundation-sites}/scss/foundation";

references #61

### CODE REVIEW

**Comment by gakimball** [comment]
Nice, thanks! Does Atmosphere have some system for publishing beta packages?

**Comment by natecox** [comment]
@gakimball As far as I'm aware there is no beta package program (though it would be cool if there were). I see fairly commonly that people will simply upload a _package-name_-beta package, but I don't believe that's any form of official standard.

Personally, I would just ensure that the atmosphere package page clearly denotes the beta status and go with it.

**Comment by gakimball** [comment]
Based on the Meteor docs, it looks like I should be able to publish `6.0.0-alpha.x` and then just `6.0.0` when it actually comes out, since the package system follows semver. I'll have it up shortly!

**Comment by natecox** [comment]
@gakimball Any luck getting that Meteor package up?

**Comment by gakimball** [comment]
Sorry, things have been busy on our end. It'll happen in the next day or so :)

**Comment by zurbchris** [comment]
Hey @natecox can you double check this, it looks like jQuery is locked in at 1.11.4?

**Comment by natecox** [comment]
It is, I used it as a reference because I've seen that version fairly commonly associated with Foundation 5.

The version can either be changed to another specific version, or to the latest (without a version constraint) by modifying the following line of `package.js`:
https://github.com/zurb/foundation-sites-6/pull/269/files#diff-49fb32b6d8276ecd1268e47c0339d55cR11

**Comment by zurbchris** [comment]
Cool, thanks. Also, we added a dependency of what-input on npm, can you confirm this is valid? 
```js
Package.onUse(function(api) {
  api.versionsFrom('1.2.1');
  api.imply('fourseven:scss@3.4.1');
  api.use(['ecmascript', 'jquery@2.1.0', 'fourseven:scss@3.4.1'], 'client');
  Npm.depends({
    'what-input': '1.1.2'
  });

```

**Comment by natecox** [comment]
I beleive that the `Npm.depends` call should be outside of the `Package.onUse` call. I've never had to do this myself, but the references that I could find all seem to indicate this. E.g., https://github.com/benjick/meteor-steam-bot/blob/master/package.js#L14-L17

When I get a chance I'll modify my fork and try it out.

**Pull request merged**
