### PR TITLE
remove and reinjects modal content in the close callback

### PR DESCRIPTION
**Pull request by adriantombu**
Refers to the https://github.com/zurb/foundation-sites-6/issues/250 issue about movie running in the background on modal close

### CODE REVIEW

**Comment by zurbrandon** [comment]
Hey @zurbchris, the only thing i worry about here is how costly it may be to do this, so make sure we take a look if there's a performance spike.

**Comment by zurbchris** [comment]
That's one reason I haven't pulled this in, I could flag a boolean on init to only reload iframes on close, which would take care of YouTube at least.

**Comment by adriantombu** [comment]
I made a few tests before making the pull request : the action takes ~20 miliseconds to happens, and ~50 miliseconds when a video is playing. I don't know if it's acceptable for you, feed free to make your more tests :)

**Comment by zurbchris** [comment]
After playing with it a bit, I think this is useful. However, it should be an option with a boolean flag and only perform this action if the user enables it.

**Comment by adriantombu** [comment]
Here you are ! I even shortened the code to save a few miliseconds :)

**Pull request merged**
