### PR TITLE
rem-calc passes through rem values

### PR DESCRIPTION
**Pull request by colin-marshall**
Fixes issue: https://github.com/zurb/foundation-sites-6/issues/277

### CODE REVIEW

**Comment by gakimball** [comment]
Awesome, thank you!

**Comment by gakimball** [comment]
Actually, can you update the test suite with a matching test? Go to `test/sass/_unit.scss` and you'll see tests for `Convert to Rem`. You can copy the format of the existing test, and write a new one along the lines of `it keeps rem values the same` or something like that.

**Comment by colin-marshall** [comment]
No problem! Test added.

**Comment by gakimball** [comment]
Thanks :)

**Pull request merged**
