### PR TITLE
Async Event Triggers / DOM Mutation Observer

### PR DESCRIPTION
**Pull request by coreysyms**
This is so any element can listen for DOM mutation events and handle
element addition, removal, or physical change accordingly.

### CODE REVIEW

**Comment by coreysyms** [comment]
This should also help with this issue https://github.com/zurb/foundation-sites-6/issues/135, as well as any other positioning plugin when thing change like accordions, alerts, etc.

**Comment by zurbchris** [comment]
I dig this, however, I think for a mutation observer we should only observe whatever element is relevant to the plugin, unless there's multiple `[data-mutate]` nodes. Speaking of, this should only create a new observer if there are nodes to watch, and it should remove an existing observer if the function is called again.

**Comment by coreysyms** [comment]
Correct. The observer is singular. Only observing the document body. There are multiple data-mutate nodes. Each one is attached to listen for the callback from the mutation observer in the same manor a scroll or resize works. 

The observer only needs to listen for changes to the Dom. And the elements listening only need to know that it has changed and to fire whatever it needs to via the callback.

**Comment by coreysyms** [comment]
For instance sticky could have this. 
this.$element.off('mutate.zf.trigger')
                 .on('mutate.zf.trigger', function() { //callback from mutation listener. Setsizes() });

**Comment by coreysyms** [comment]
@zurbchris you can find me on the foundation Gitter app if you want to hash though what you think this needs or further explanation. I think it could be a valuable addition.

**Comment by zurbchris** [comment]
I agree with you, jump on gitter sometime today if you have the chance and we'll chat.

**Comment by coreysyms** [comment]
@zurbchris my update is now live based on our conversations.

**Comment by coreysyms** [comment]
I tied a single listener to each element to listen for resize and scroll, if such event happens the element with [data-scroll] or [data-resize] attribute gets its new [data-events] attribute (this is added in dynamically) pinged with the type of event, then each element asynchronously fires its triggerHandler eliminating the need for a loop

**Pull request merged**
