### PR TITLE
what-input integration

### PR DESCRIPTION
**Pull request by gakimball**
what-input allows us to disable CSS outlines only if the user is using a mouse.

This mixin adds the needed CSS to a component:

```scss
.button {
  @include disable-mouse-outline;
  // ...
}
```

Need to make sure every component that needs it, has it, and then it'll be done.

### CODE REVIEW

**Comment by andycochran** [comment]
:+1:

**Comment by Owlbertz** [comment]
Nice. I hope this really helps preventing developers from removing the outline completely and thus screwing with keyboard users.

**Comment by JeremyEnglert** [comment]
@gakimball - what is the best way to implement this? Will what-input be included by default or should it be treated as a vendor file?

**Comment by gakimball** [comment]
@JeremyEnglert It's listed as a dependency in `bower.json` and `package.json`, so you'll get it along with jQuery by default if you're using Bower or npm.

**Pull request merged**
